/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11.1/samples
 */

plugins {
    kotlin("jvm") version "2.1.0" // Replace with your Kotlin version
    application
}

group = ""
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(kotlin("test"))
}

application {
    // Specify the fully qualified name of your main class
    mainClass.set("MainKt")
}